//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adventure_Game.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adventure_Game.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _09c9b295f8ff686b7e8674f9c0151555__lost_river_creepy_pictures {
            get {
                object obj = ResourceManager.GetObject("_09c9b295f8ff686b7e8674f9c0151555__lost_river_creepy_pictures", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1dae12354aea3992aa7e90478ac81a51 {
            get {
                object obj = ResourceManager.GetObject("_1dae12354aea3992aa7e90478ac81a51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _25549 {
            get {
                object obj = ResourceManager.GetObject("_25549", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4586228f53f2ab93cae0281a683affa7 {
            get {
                object obj = ResourceManager.GetObject("_4586228f53f2ab93cae0281a683affa7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _877345_1 {
            get {
                object obj = ResourceManager.GetObject("_877345_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Acadia_Spooky_Woods_II {
            get {
                object obj = ResourceManager.GetObject("Acadia_Spooky_Woods_II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Applause_SoundBible_com_151138312 {
            get {
                return ResourceManager.GetStream("Applause_SoundBible_com_151138312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bdacea4eb922cfae8ebf56dde1c2c12e__creepy_things_bridges {
            get {
                object obj = ResourceManager.GetObject("bdacea4eb922cfae8ebf56dde1c2c12e__creepy_things_bridges", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chatillon_car_graveyard_abandoned_cars_cemetery_belgium_31 {
            get {
                object obj = ResourceManager.GetObject("chatillon_car_graveyard_abandoned_cars_cemetery_belgium_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Footsteps_Walking_SoundBible_com_522653436 {
            get {
                return ResourceManager.GetStream("Footsteps_Walking_SoundBible_com_522653436", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ruyaveruya_ruyada_cukur_gormek_666x480 {
            get {
                object obj = ResourceManager.GetObject("ruyaveruya_ruyada_cukur_gormek_666x480", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.ca/url?sa=i&amp;rct=j&amp;q=&amp;esrc=s&amp;source=images&amp;cd=&amp;ved=0ahUKEwjDsOSfsKDXAhXHuhQKHQG8CtAQjRwIBw&amp;url=http%3A%2F%2Fmolore.com%2Fvsearch-page%2Fdrift-garage-episode-407%2FEgIQAUh4UBTqAwA%25253D.html&amp;psig=AOvVaw1OdHEEUEvlcHv4DKU7fIC4&amp;ust=1509728810363675.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.ca/url?sa=i&amp;rct=j&amp;q=&amp;esrc=s&amp;source=images&amp;cd=&amp;ved=0ahUKEwjDsOSfsKDXAhXHuhQKHQG8CtAQjRwIBw&amp;url=http%3A%2F%2Fmolore.com%2Fvsearch-page%2Fdrift-garage-episode-407%2FEgIQAUh4UBTqAwA%25253D.html&amp;psig=AOvVaw1OdHEEUEvlcHv4DKU7fIC4&amp;ust=1509728810363675.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.ca/url?sa=i&amp;rct=j&amp;q=&amp;esrc=s&amp;source=images&amp;cd=&amp;ved=0ahUKEwji0rr0ia3XAhWr5oMKHQiVCMgQjRwIBw&amp;url=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F596234438137478636%2F&amp;psig=AOvVaw1XYX0ECs1zf6307gRafFQo&amp;ust=1510165198363804.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tmpnull {
            get {
                object obj = ResourceManager.GetObject("tmpnull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_room_closed_door_empty_35545491 {
            get {
                object obj = ResourceManager.GetObject("white_room_closed_door_empty_35545491", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] You_Died {
            get {
                object obj = ResourceManager.GetObject("You_Died", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
